[package]
name = "hmi"
version = "0.1.0"
edition = "2024"

[dependencies]
# Cortex M
cortex-m = "0.7.7"
cortex-m-rt = "0.7.5"

# Panic Handler
panic-probe = { version = "1.0.0", features = ["print-defmt"] }

# Embassy
embassy-executor = { version = "0.10.0", features = [
	"platform-cortex-m",
	"defmt",
] }
embassy-time = { version = "0.5.1" }
embassy-rp = { version = "0.10.0", features = [
	"time-driver",
	"critical-section-impl",
	"rp235xb",
	"binary-info",
	"defmt",
	"executor-thread",
	"executor-interrupt",
	"unstable-pac",
] }
embassy-sync = { version = "0.8.0", features = ["defmt"] }
embassy-futures = { version = "0.1.2", features = ["defmt"] }

# Embedded HAL
embassy-embedded-hal = { version = "0.6.0", features = ["defmt"] }
embedded-hal-async = { version = "1.0.0", features = ["defmt-03"] }

# Defmt Logging
defmt = "1.0.1"
defmt-rtt = "1.1.0"

# Other
static_cell = "2.1.1"
heapless = { version = "0.9.2", features = ["defmt"] }
fixed = { version = "1.31.0", features = ["defmt"] }
assign-resources = "0.5.0"
hmi-gui = { path = "../hmi-gui" }
lvgl = { path = "../lvgl" }
embedded-alloc = { version = "0.7.0", default-features = false, features = [
	"tlsf",
] }
rlsf = { version = "0.2.1", default-features = false }
const-default = { version = "1.0.0", default-features = false }
critical-section = "1.2.0"
